### ISSUE TITLE
Bug: `-n` flag trailing newline

### ISSUE THREAD

**Issue by yanocv** [cpuabuse/cross-echo#13]
## Description

Trailing newline printed when `-n` flag is set.

### Reference

Similar to cpuabuse/cross-cat#31.

## To reproduce

```bash
echo -n "Hello, Wolrd!"
```

## Actual

```bash
Hello, World!
# Trailing newline
```

## Expected

```bash
Hello, World!
```

**Comment by winterhotlatte** [comment]
This can be reproduce only on Windows. It seems that Command Line and PowerShell produce newline, when the program's output does not produce one. There might be no fix for this.
